# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Semana10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Semana10
  pod 'Firebase/Analytics'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SDWebImage'
end
